### PR TITLE
fix:Multi Processing system that is added in main py file is not functioning well!!!

### PR DESCRIPTION
**Pull request by user-64bit**
Issue #2
Sorry for the late Response :worried: 
I've made some changes like creating functions and using threading, etc
Please check out my PR
Let me know if there is some issue with it
Thank You :smile:

### CODE REVIEW

**Comment by 0xuser64bit** [comment]
Hello...
Are you there? :eyes:

**Comment by 0xuser64bit** [comment]
Hello.......
Are you there? :roll_eyes:

**Comment by iamEzmuth** [comment]
I am so sorry, the last 2 months were really hectic, I was on a company tour to Norway and had some work to do, but I am really sorry to keep you waiting...

Talking about the code, I am really amazed by the work you have dedicatedly given to this code.. let me review this quick and merge the PR, just give me a few hours.

**Comment by 0xuser64bit** [comment]
so what changes do I need to make if there any
:thinking:

**Comment by 0xuser64bit** [comment]
Hello There,
It's been 2 months and I am not getting a clear response from you.
I was so excited to work on this project. but since it's not an active repository now I won't be able to work on this project.
Sorry for that. :disappointed:

**Comment by iamEzmuth** [comment]
I am sorry for the late response. I checked your code it does work fine but it has some issues to be fixed. But its hacktoberfest so let's give that opportunity to someone else.. I will be merging your code tomorrow,  don't forget to register in hacktoberfest before 31st October to get some cool swags...

**Comment by iamEzmuth** [comment]
If you want you can close this PR and create another one so to be counted as for hacktoberfest.

**Pull request closed without merging**
